# Generated by Django 4.0.4 on 2022-05-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteHome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paginainicial',
            old_name='SubTitulo_Header',
            new_name='SubTitulo_Header01',
        ),
        migrations.RenameField(
            model_name='paginainicial',
            old_name='Titulo_Header',
            new_name='Titulo_Header01',
        ),
    ]
