# Generated by Django 4.0.4 on 2022-05-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteHome', '0002_rename_subtitulo_header_paginainicial_subtitulo_header01_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paginainicial',
            old_name='SubTitulo_Header01',
            new_name='subTitulo',
        ),
        migrations.RemoveField(
            model_name='paginainicial',
            name='Titulo_Header01',
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título'),
        ),
    ]
