# Generated by Django 4.0.4 on 2022-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteHome', '0003_rename_subtitulo_header01_paginainicial_subtitulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginainicial',
            name='subTitulo',
        ),
        migrations.RemoveField(
            model_name='paginainicial',
            name='titulo',
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='SubTitulo_Header',
            field=models.CharField(blank=True, max_length=100, verbose_name='SubTitulo_Header'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='Titulo_Header',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo_Header'),
        ),
    ]
