# Generated by Django 4.0.4 on 2022-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteHome', '0004_remove_paginainicial_subtitulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginainicial',
            name='SubTitulo_Header',
        ),
        migrations.RemoveField(
            model_name='paginainicial',
            name='Titulo_Header',
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='subTitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='subTitulo'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo'),
        ),
    ]
